export const homeCopy: Record<string, string> = {
    'A user-feature perturbation changes the response. The full story separates MMD distribution shifts from membership probability.': '用户特征扰动改变模型响应。完整讲解区分 MMD 分布变化与成员概率。',
    'Source table and experimental context stay beside every reported result.': '每项报告结果都附有来源表格与实验上下文。',
    'Source: ALOA paper, Table 6. Bars start at zero.': '来源：ALOA 论文表 6。条形图从零开始。',
    'Illustrative records enter a private transformation stage and computational elements emerge; internal mechanism is not depicted': '示意记录进入私有变换环节并生成计算元素；不展示内部机制',
    'Illustrative user and item towers produce embeddings, with an optional user-input perturbation': '用户塔与物品塔生成嵌入的示意，可查看用户输入扰动',
    'Schematic New York and New Jersey map with an illustrative rental location': '纽约与新泽西的示意地图，标有示例房源位置',
    'Chapters': '章节', 'Selected work': '精选作品', 'Research · Mathematics · Products': '研究 · 数学 · 产品', 'SCROLL TO TRANSFORM': '滚动探索', 'AI RESEARCHER': '人工智能研究者', 'APPLIED MATHEMATICIAN': '应用数学实践者', 'FOUNDER': '创业者', 'FROM IDEA TO IMPLEMENTATION': '从想法到实现', 'Intelligence,': '智能，', 'built for the': '为真实', 'real world.': '世界而构建。', 'Explore my work ': '探索作品 ', 'Let’s connect ': '开始交流 ', 'Let’s connect ↗︎': '开始交流 ↗︎', 'Explore all projects ↗︎': '查看全部作品 ↗︎', 'Explore the rental demo ↗︎': '体验租房演示 ↗︎', 'Explore Elementization ↗︎': '了解 Elementization ↗︎', 'Inside the Studio ↗︎': '走进 Studio ↗︎', 'Explore the research ↗︎': '探索研究 ↗︎',
    '01 Introduction': '01 简介', '02 Rental agent': '02 租房助手', '03 Elementization': '03 Elementization', '04 Studio': '04 Studio', '05 Research': '05 研究', '06 Contact': '06 联系', '01 / Applied intelligence': '01 / 应用智能', 'Product chapter': '产品篇章', 'New York & New Jersey': '纽约与新泽西', 'A city of options.': '城市中的选择。', 'A clearer choice.': '更清晰的决定。', 'A rental-listing agent that brings inventory, location, and commute context into one workflow.': '将房源、位置与通勤信息整合到一个工作流程中的租房助手。', 'INTERACTIVE SAMPLE · FICTIONAL LISTING': '交互示例 · 虚构房源', 'NYC / NJ · RENTAL EXPLORER': '纽约 / 新泽西 · 租房探索', 'Sample 01 / Jersey City': '示例 01 / 泽西市', '/ mo': '/ 月', '1 bed · In-unit laundry': '一居室 · 室内洗衣', 'Commute context available': '通勤信息', '＋ Save to sample shortlist': '＋ 加入示例候选清单', '✓ Saved · Click to remove': '✓ 已保存 · 点击移除', 'Schematic geography · Illustrative route': '示意地图 · 示意路线', 'Discover →︎ Compare →︎ Shortlist': '发现 →︎ 比较 →︎ 筛选',
    '02 / Elementization': '02 / Elementization', 'Conceptual visual': '概念示意', 'Change the substrate.': '改变数据载体。', 'Define what’s possible.': '定义可能性。', 'Structured data becomes computational elements for a declared scope of operations.': '将结构化数据转为支持声明范围内操作的计算元素。', 'STRUCTURED RECORDS': '结构化记录', 'INTERNAL METHOD OMITTED': '内部方法不公开', 'COMPUTATIONAL ELEMENTS': '计算元素', 'Private transformation': '私有变换', 'Similarity': '相似性', 'Clustering': '聚类', 'Scope': '范围', 'Compare elements using the declared geometry. Visual positions are illustrative.': '在声明的几何关系下比较元素。位置仅作示意。', 'Explore grouping within a declared capability scope. This is not a measured clustering result.': '在声明的能力范围内探索分组。此处不是实测聚类结果。', 'A declared capability boundary is essential. Performance on a particular task needs its own evaluation.': '明确能力边界至关重要。特定任务的表现需要独立评估。', 'Structured records': '结构化记录', 'Inside an organization boundary': '组织边界内', 'Private transformation · Internals omitted': '私有变换 · 内部细节不公开', 'Computational elements': '计算元素', 'For a declared scope of operations': '支持声明范围内的操作', 'Explore conceptual capabilities': '探索概念能力', 'Conceptual transformation': '概念变换',
    '03 / Elementization Studio': '03 / Elementization Studio', 'Sanitized walkthrough': '公开演示', 'From theory to a working tool': '从理论到可用工具', 'Inspect.': '检查。', 'Evaluate.': '评估。', 'Then approve.': '再审批。', 'A local desktop workflow with explicit review, validation, and human approval.': '具有明确检查、验证与人工审批环节的本地桌面工作流。', 'MVP-A · Implemented desktop workflow': 'MVP-A · 已实现桌面工作流', 'Release checks remain at the recorded checkpoint.': '发布检查仍处于所记录的检查点。', 'Illustrative workspace': '示意工作区', '01 Intake': '01 导入', '02 Review': '02 检查', '03 Validation': '03 验证', '04 Approval': '04 审批', '05 Output': '05 输出', 'LOCAL WORKSPACE': '本地工作区', 'Begin with structure.': '从结构开始。', 'Inspect a structured dataset before choosing how to proceed.': '检查结构化数据集，再决定下一步。', 'Input type': '输入类型', 'Structured table': '结构化表格', 'Field review': '字段检查', 'Required': '必需', 'Source handling': '源数据处理', 'Local': '本地', 'Next scene →︎': '下一步 →︎', 'Back to intake ↗︎': '返回导入 ↗︎', 'Interface interpretation based on implemented screens. Sample states, not a live certification run.': '根据已实现界面制作的示意。展示示例状态，不运行实时认证。', 'Local processing · Human review · Governed artifacts': '本地处理 · 人工审阅 · 受治理的产物', 'DATASET REVIEW': '数据集检查', 'Understand the source.': '理解数据来源。', 'Review field roles and sensitivity before moving forward.': '继续之前检查字段角色与敏感性。', 'Schema': '数据结构', 'Review fields': '检查字段', 'Sensitivity': '敏感性', 'Human review': '人工审阅', 'Characterization': '特征分析', 'Inspect report': '检查报告', 'VALIDATION': '验证', 'Evidence before approval.': '证据先于审批。', 'Examine measured results in their declared evaluation context.': '在声明的评估上下文中检查实测结果。', 'Structural preservation': '结构保持', 'Separate measure': '独立指标', 'Reconstruction resistance': '重建抵抗', 'Threat-model bounded': '受威胁模型限定', 'Linkage resistance': '关联抵抗', 'HUMAN DECISION': '人工决策', 'Make the decision explicit.': '明确决策。', 'Review the evidence and declared capabilities before approval.': '审批前检查证据与声明能力。', 'Validation evidence': '验证证据', 'Review required': '需要检查', 'Capability scope': '能力范围', 'Approval': '审批', 'Human action': '人工操作', 'GOVERNED ARTIFACTS': '受治理的产物', 'A substrate for computation.': '用于计算的载体。', 'Inspect approved outputs and manage the project lifecycle.': '检查获批输出并管理项目生命周期。', 'Elements': '计算元素', 'Computational output': '计算输出', 'Contract': '契约', 'Declared interface': '声明接口', 'Private artifact': '私有产物', 'Contents excluded': '内容不公开',
    '04 / Machine learning security': '04 / 机器学习安全', 'Research chapter': '研究篇章', 'ALOA / Two-tower models': 'ALOA / 双塔模型', 'What does': '模型', 'a model': '究竟', 'remember?': '记住了什么？', 'Inferring training membership from embedding-based recommendation models.': '从基于嵌入的推荐模型中推断训练成员身份。', '01 Towers': '01 双塔', '02 Perturb': '02 扰动', '03 Evidence': '03 证据', 'USER INPUT': '用户输入', 'ITEM INPUT': '物品输入', 'CONTINUOUS EMBEDDINGS': '连续嵌入', 'User feature changed': '用户特征改变', 'User and item towers turn their respective inputs into embeddings.': '用户塔与物品塔将各自的输入转为嵌入。', 'Conceptual geometry · Not measured embedding coordinates': '概念几何 · 非实测嵌入坐标', 'Reported shadow-based evaluation / Table 6': '已报告的影子模型评估 / 表 6', 'Accuracy · Different class balances: 4:1 vs 1:10 IN:OUT.': '准确率 · 不同类别比例：IN:OUT 为 4:1 与 1:10。', 'These are reported experimental results, not universal success rates.': '这些是所报告的实验结果，不代表普遍成功率。', 'Open the full research paper ↗︎': '查看完整研究论文 ↗︎', 'Full story: towers →︎ shadow model →︎ perturbations →︎ classifier →︎ evidence': '完整过程：双塔 →︎ 影子模型 →︎ 扰动 →︎ 分类器 →︎ 证据', 'Research scenes': '研究步骤',
    'Ideas deserve implementation.': '让想法得到实现。', 'Closing chapter': '联系篇章', 'Let’s build': '一起构建', 'what’s next.': '下一步。', 'Applied AI, research collaborations, and ambitious products that need technical depth.': '应用人工智能、研究合作，以及需要技术深度的产品。', 'RESEARCHER · MATHEMATICIAN · FOUNDER': '研究者 · 数学实践者 · 创业者', 'Motion: ON': '动态：开', 'Motion: OFF': '动态：关', 'Studio walkthrough': 'Studio 演示'
};
