import Link from 'next/link';
import Image from 'next/image';
import type { Locale } from '@/data/projects';
import portrait from '@/pic/headshot_nbck.png';
import SiteShell from '@/components/layout/SiteShell';
import ContactForm from '@/components/contact/ContactForm';
import { getContactConfig } from '@/lib/contact';
import { pageCopy, pick, works } from './content';
import PageMotion from './PageMotion';
import VisualLab from './VisualLab';
import RentalDemo from './RentalDemo';
import StudioDemo from './StudioDemo';
import LearningDemo from './LearningDemo';
import ElementStory from './ElementStory';
const paper = 'https://openreview.net/forum?id=0QScq2eA5l';
export default function PortfolioPage({ page, locale }: {
    page: string;
    locale: Locale;
}) {
    const zh = locale === 'zh', c = pageCopy[page], t = (en: string, cn: string) => zh ? cn : en;
    const link = (href: string, title: string) => <Link className="editorial-link" href={`/${locale}${href}`}>{title} ↗</Link>;
    const workCards = () => <div className="work-grid">{works.map((w, i) => <Link data-rise className={`work-card work-${w.slug}`} key={w.slug} href={`/${locale}/projects/${w.slug}`}><div className="work-card-top"><span>0{i + 1} / {pick(w.kind, locale)}</span><span>↗</span></div><div className="work-symbol" aria-hidden="true">{i === 0 ? '⌖' : i === 1 ? '∴' : i === 2 ? '⫶' : '↗'}</div><small>{pick(w.status, locale)}</small><h2>{pick(w.name, locale)}</h2><p>{pick(w.summary, locale)}</p></Link>)}</div>;
    const section = (title: string, body: React.ReactNode, id?: string) => <section className="editorial-section" data-rise id={id}><h2>{title}</h2>{body}</section>;
    return <SiteShell><main className={`editorial-page page-${page}`} id="main-content"><PageMotion><div className="editorial-intro"><p className="eyeline" data-reveal>{pick(c.eyebrow, locale)}</p><h1 data-reveal>{pick(c.title, locale).split('\n').map((line, i) => <span key={line} className={i === 1 ? 'serif-line' : ''}>{line}</span>)}</h1><p className="editorial-lead" data-reveal>{pick(c.intro, locale)}</p></div>
 {page === 'projects' && workCards()}
 {page === 'about' && <><div className="about-feature" data-rise><div className="about-portrait"><Image src={portrait} alt={t('Changjian He', '何昌健')} sizes="(max-width: 760px) 90vw, 45vw"/></div><div><span className="eyeline">CHANGJIAN “CJ” HE</span><h2>{t('Think precisely.\nBuild practically.', '严谨思考。\n务实构建。')}</h2><p>{t('I work where machine learning security, data infrastructure, and product execution meet. Mathematical structure helps me frame a problem; building a working system tests whether that framing holds.', '我的工作连接机器学习安全、数据基础设施与产品实践。数学结构帮助我定义问题，实际系统则检验这些定义。')}</p>{link('/projects', t('Explore the work', '查看作品'))}</div></div>{section(t('Three ways of working.', '三种工作视角。'), <div className="principle-grid">{[[t('Research', '研究'), t('Ask what a system reveals—and under which assumptions.', '追问系统揭示了什么，以及这些结论依赖哪些假设。')], [t('Engineering', '工程'), t('Turn a technical idea into a workflow people can inspect.', '将技术想法转为人们能够检查的工作流程。')], [t('Product', '产品'), t('Let real constraints shape what is useful to build.', '让实际约束决定值得构建的产品。')]].map(([h, p], i) => <article key={h}><span>0{i + 1}</span><h3>{h}</h3><p>{p}</p></article>)}</div>)}</>}
 {page === 'research' && <><VisualLab kind="aloa" locale={locale}/>{section(t('A question with consequences.', '一个具有现实意义的问题。'), <div className="editorial-columns"><p>{t('Can the outputs of a recommender reveal whether a person’s record was used in training? ALOA studies membership inference on two-tower neural networks.', '推荐系统的输出能否揭示某人的记录是否参与了训练？ALOA 研究双塔神经网络中的成员推断。')}</p><div>{link('/projects/aloa', t('Explore ALOA', '了解 ALOA'))}<a className="editorial-link" href={paper} target="_blank" rel="noreferrer">{t('Read the paper', '阅读论文')} ↗</a></div></div>)}{section(t('From model behavior to data boundaries.', '从模型行为到数据边界。'), <div className="editorial-columns"><p>{t('The complementary infrastructure question is what downstream computation actually needs to receive. Elementization explores that question with an explicit capability scope and separate evaluation axes.', '另一个互补的问题是：下游计算究竟需要接收什么？Elementization 通过明确的能力范围和独立的评估维度探索这一问题。')}</p>{link('/projects/elementization', t('Explore Elementization', '了解 Elementization'))}</div>)}</>}
 {page === 'accomplishments' && <div className="milestones">{[[t('Research', '研究'), 'ALOA', t('First-author research on membership inference in two-tower recommendation models.', '关于双塔推荐模型成员推断的第一作者研究。'), '/projects/aloa'], [t('Implementation', '工程实现'), 'Elementization Studio', t('MVP-A implementation with recorded automated acceptance. Physical-machine release checks remain at the recorded checkpoint.', 'MVP-A 已实现，并记录了自动化验收。实体机器发布检查仍处于记录中的检查点。'), '/projects/elementization'], [t('Product exploration', '产品探索'), t('Applied AI workflows', '应用 AI 工作流'), t('Rental exploration and an adaptive learning system design connect technical ideas with concrete user decisions.', '租房探索与自适应学习系统设计，将技术想法与具体用户决策连接起来。'), '/projects']].map(([tag, title, text, href], i) => <article data-rise key={title}><span className="milestone-number">0{i + 1}</span><div><small>{tag}</small><h2>{title}</h2><p>{text}</p>{link(href, t('View the work', '查看作品'))}</div></article>)}</div>}
 {page === 'rental-agent' && <><RentalDemo locale={locale}/>{section(t('A clearer decision path.', '更清晰的决策路径。'), <div className="principle-grid">{[t('Discover by area', '按区域发现'), t('Compare practical constraints', '比较实际约束'), t('Keep a considered shortlist', '保留经过比较的清单')].map((s, i) => <article key={s}><span>0{i + 1}</span><h3>{s}</h3></article>)}</div>)}{section(t('Behind the demonstration.', '演示背后的工作。'), <div className="editorial-columns"><p>{t('The separate rental-agent project uses Python and PostGIS for a location-aware listing workflow. This public sample shows interaction design with fictional inventory. Live feeds, routing, and backend access are not connected here.', '独立的租房助手项目使用 Python 和 PostGIS 构建位置感知的房源流程。此公开示例使用虚构房源展示交互设计，未连接实时数据、路线服务或后端。')}</p>{link('/contact', t('Discuss the product', '交流产品'))}</div>)}</>}
 {page === 'elementization' && <><ElementStory locale={locale}/>{section(t('Evidence has more than one axis.', '证据不止一个维度。'), <div className="principle-grid">{[[t('Structure', '结构'), t('What relationships are preserved for the declared task?', '针对声明的任务，哪些关系得到保持？')], [t('Reconstruction', '重建'), t('What can an adversary recover under the stated threat model?', '在声明的威胁模型下，攻击者能恢复什么？')], [t('Linkage', '关联'), t('How much can an adversary associate with outside information?', '攻击者能借助外部信息关联到什么程度？')]].map(([h, p], i) => <article key={h}><span>0{i + 1}</span><h3>{h}</h3><p>{p}</p></article>)}</div>)}{section(t('From theory to a working tool.', '从理论到可用工具。'), <><StudioDemo locale={locale}/><p className="evidence-note">{t('Recorded status: MVP-A implementation and automated acceptance. Clean physical-machine installation and separate-machine recovery checks remained outstanding at the inspected checkpoint.', '记录状态：MVP-A 实现与自动化验收。在所检查的记录中，干净实体机器安装与跨机器恢复检查尚未完成。')}</p></>, 'studio')}{section(t('Demo evidence, in context.', '在上下文中阅读演示证据。'), <><div className="demo-evidence"><div><strong>99%</strong><span>{t('Raw-data demo · Logistic regression', '原始数据演示 · 逻辑回归')}</span></div><div><strong>96%</strong><span>{t('Representation demo · Neural network', '表示演示 · 神经网络')}</span></div></div><p className="evidence-note">{t('Innerfy demo records: 800 training rows and 200 test rows per run. A 3-percentage-point gap between different pipelines—not a controlled, equal-model estimate of transformation cost. These runs do not establish current Studio utility or privacy.', 'Innerfy 演示记录：每次运行使用 800 条训练记录、200 条测试记录。不同流水线之间相差 3 个百分点，并非相同模型下的受控变换成本估计。这些运行不证明当前 Studio 的效用或隐私表现。')}</p><details><summary>{t('Scope and limitations', '范围与局限')}</summary><p>{t('Capabilities are task-specific. Structural preservation, reconstruction resistance, and linkage resistance require separate evaluation. The public visualization does not expose mapping recipes, parameters, private artifacts, or a live transformation service.', '能力与具体任务相关。结构保持、重建抵抗与关联抵抗需要独立评估。公开可视化不暴露映射方法、参数、私有产物或在线变换服务。')}</p></details></>)}</>}
 {page === 'aloa' && <><VisualLab kind="aloa" locale={locale}/>{section(t('Follow the full method.', '理解完整方法。'), <div className="method-list">{[t('Separate user and item inputs become embeddings.', '用户与物品输入分别转为嵌入。'), t('Synthetic queries train a shadow model on target responses.', '合成查询使用目标响应训练影子模型。'), t('User-feature perturbations expose response behavior.', '用户特征扰动揭示响应行为。'), t('Shadow-derived features support membership classification.', '影子模型衍生特征支持成员分类。')].map((s, i) => <div key={s}><span>0{i + 1}</span><p>{s}</p></div>)}</div>)}{section(t('Read the result precisely.', '准确理解结果。'), <><p className="evidence-note">{t('Table 6 reports 97.87% Combined accuracy and 95.07% Dummy accuracy with IN:OUT ratios of 4:1 and 1:10. These populations differ. Table 7’s 99.65% is the proportion of known training members predicted IN, not general member/nonmember accuracy.', '表 6 报告 Combined 准确率 97.87%、Dummy 准确率 95.07%，IN:OUT 比例分别为 4:1 与 1:10，评估人群不同。表 7 的 99.65% 是已知训练成员被预测为 IN 的比例，并非一般成员/非成员准确率。')}</p><a className="editorial-link" href={paper} target="_blank" rel="noreferrer">{t('Open the full paper and discussion', '查看完整论文与讨论')} ↗</a><details><summary>{t('What the diagrams do—and do not—show', '图示的含义与范围')}</summary><p>{t('The positions, pulses, and embedding shifts are conceptual. They are not measured coordinates or an empirical ROC curve. Membership inference asks about training inclusion; it does not demonstrate record reconstruction. MMD distribution comparisons should not be read as membership probabilities.', '位置、脉冲与嵌入变化均为概念示意，不是实测坐标或经验 ROC 曲线。成员推断关注训练参与情况，不表示记录重建。MMD 分布比较也不应被解读为成员概率。')}</p></details></>)}</>}
 {page === 'ai-learning-assistant' && <><LearningDemo locale={locale}/>{section(t('Adaptation, with instructor visibility.', '自适应教学，让教师看得见。'), <div className="principle-grid">{[[t('Evaluate', '评估'), t('Learning pace, handling stability, concept mastery, knowledge load capacity, and risk signals form the student learning profile.', '学习速度、应对稳定性、概念掌握、知识负荷容量与风险信号，共同构成学生学习画像。')], [t('Adjust', '调整'), t('The profile guides reinforcement frequency, instructional density, and the selection of teaching actions.', '学习画像指导巩固频率、教学密度与教学行动的选择。')], [t('Recalibrate', '重新校准'), t('New interactions update the profile. Instructors see forecasts, concept gaps, risk alerts, and intervention recommendations.', '新的互动更新学习画像。教师可查看进度预测、概念薄弱点、风险提醒与干预建议。')]].map(([h, p], i) => <article key={h}><span>0{i + 1}</span><h3>{h}</h3><p>{p}</p></article>)}</div>)}<p className="evidence-note">{t('This page presents the supplied high-level system design. The document does not establish deployment status or measured learning outcomes.', '本页展示所提供的高层系统设计。该文档不证明部署状态或实测学习效果。')}</p></>}
   {page === 'contact' && <div className="contact-layout" data-rise><div className="contact-directions">{[t('Research collaboration', '研究合作'), t('Engineering & product roles', '工程与产品机会'), t('Clients & investors', '客户与投资者')].map((s, i) => <div key={s}><span>0{i + 1}</span><h2>{s}</h2></div>)}<a className="coral-button" href="https://www.linkedin.com/in/lastshaman" target="_blank" rel="noreferrer">{t('Connect on LinkedIn', '在 LinkedIn 联系')} ↗</a></div><div>{getContactConfig().apiKey && getContactConfig().toEmail && getContactConfig().fromEmail ? <ContactForm /> : <div className="contact-note"><h2>{t('Tell me what you’re building.', '聊聊你正在构建什么。')}</h2><p>{t('Share the problem, the kind of collaboration you have in mind, and any useful context. LinkedIn is the available contact channel.', '可以分享问题、你期待的合作方式，以及相关背景。当前可通过 LinkedIn 联系。')}</p><a className="editorial-link" href="https://www.linkedin.com/in/lastshaman">LinkedIn ↗</a></div>}</div></div>}
 {page !== 'contact' && <section className="next-chapter" data-rise><small>{t('Keep exploring', '继续探索')}</small><h2>{t('Where ideas go next.', '想法的下一步。')}</h2><div>{link(page === 'projects' ? '/about' : '/projects', page === 'projects' ? t('Meet CJ', '了解 CJ') : t('All projects', '全部作品'))}{link('/contact', t('Start a conversation', '开始交流'))}</div></section>}
 </PageMotion></main></SiteShell>;
}
