"use client";
import ArrowIcon from "@/components/portfolio/ArrowIcon";
import { useState, useRef } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import {useSiteMotion} from './useSiteMotion';
import type { Locale } from '@/data/projects';
export default function VisualLab({ kind, locale }: {
    kind: 'elementization' | 'aloa' | 'learning';
    locale: Locale;
}) {
    const enabled=useSiteMotion();
    const zh = locale === 'zh', root = useRef<HTMLDivElement>(null), [step, setStep] = useState(0);
    const labels = kind === 'aloa' ? (zh ? ['双塔', '影子模型', '扰动', '成员分类', '证据'] : ['Two towers', 'Shadow model', 'Perturbation', 'Membership', 'Evidence']) : kind === 'elementization' ? (zh ? ['记录', '计算元素', '能力边界'] : ['Records', 'Elements', 'Capability scope']) : (zh ? ['设定目标', '引导练习', '复盘'] : ['Set a goal', 'Guided practice', 'Reflect']);
    useGSAP(() => { if(!enabled)return;
        if(kind==='aloa' && (step===1 || step===3)){gsap.from('.flow-node',{y:20,opacity:0,duration:.65,stagger:.2});gsap.fromTo('.flow-node>span',{x:-8,opacity:.2},{x:0,opacity:1,duration:.8,stagger:.25,delay:.4});}
        if(kind==='aloa'&&step===4)gsap.from('.evidence-track i',{scaleX:0,transformOrigin:'left',duration:1.2,stagger:.2,ease:'power2.out'});
 gsap.from('.lab-art', { opacity: .3, y: 12, duration: .65, ease: 'power2.out' }); if (kind === 'aloa' && step === 2)
        gsap.fromTo('.input-signal', { y: -42, opacity: 1 }, { y: 0, duration: 1.2, ease: 'sine.inOut' }); if(kind === 'aloa' && step === 2){gsap.fromTo('.output-dot',{y:15},{y:0,duration:.8,delay:1.2,ease:'sine.inOut'});gsap.to('.input-signal',{opacity:0,duration:.4,delay:1.8});}
            if (kind === 'elementization' && step === 1)
        gsap.from('.lab-dot', { opacity: 0, scale: 0, stagger: .035, duration: .6, transformOrigin: 'center' }); }, { scope: root, dependencies: [step,enabled], revertOnUpdate: true });
    const descriptions = kind === 'aloa' ? (zh ? ['用户与物品通过不同的塔生成嵌入表示。', '使用合成输入查询目标模型，训练影子模型来学习其响应。', '改变用户特征，观察嵌入响应。这里的几何位置仅作示意。', '影子模型衍生的特征进入成员分类器；成员概率与 MMD 分布比较是不同概念。', '表 6 报告的是影子模型评估。不同的类别比例必须与结果一起阅读。'] : ['Separate user and item towers produce embeddings.', 'Synthetic inputs query the target; a shadow model learns its responses.', 'A user feature changes, then the embedding responds. Geometry here is illustrative.', 'Shadow-derived features feed a membership classifier. Membership probability and MMD distribution comparison are distinct.', 'Table 6 reports shadow-based evaluation. Read the results alongside their different class balances.']) : kind === 'elementization' ? (zh ? ['结构化记录保留在组织边界内。', '私有变换生成计算元素。这里不运行实际映射。', '相似性、聚类或其他任务的可用性，必须在其声明范围内独立评估。'] : ['Structured records begin inside an organization boundary.', 'A private transformation produces computational elements. No actual mapping runs here.', 'Utility for similarity, clustering, or another task must be evaluated within its declared scope.']) : (zh ? ['学习者选择一个明确目标。此界面是概念演示。', '将任务拆成可检查的步骤，保留向教师或指导者求助的路径。', '回顾思路并选择下一步，不将自动回答视为学习效果的证据。'] : ['The learner chooses a specific goal. This interface is a concept demonstration.', 'Break a task into checkable steps, with a route to an instructor or reviewer.', 'Review the reasoning and choose a next step. An automatic answer is not evidence of learning.']);
    return <div className="visual-lab" ref={root}><div className="lab-toolbar"><span>{zh ? '交互讲解' : 'Interactive explainer'}</span><span>{String(step + 1).padStart(2, '0')} / {String(labels.length).padStart(2, '0')}</span></div><div className="lab-art">
 {kind === 'aloa' && step === 4 ? <div className="evidence-bars"><p>ALOA · {zh ? '表 6 / 准确率' : 'Table 6 / Accuracy'}</p>{[['Combined', '97.87', '4:1'], ['Dummy', '95.07', '1:10']].map(([name, value, ratio]) => <div key={name}><div className="bar-label"><span>{name} · IN:OUT {ratio}</span><strong>{value}%</strong></div><div className="evidence-track"><i style={{ width: value + '%' }}/></div></div>)}<small>{zh ? '不同类别比例；不代表普遍成功率。' : 'Different class balances; not universal success rates.'}</small></div> :
            kind === 'aloa' && (step === 1 || step === 3) ? <div className="flow-diagram">{(step === 1 ? (zh ? ['合成输入', '目标响应', '影子模型'] : ['Synthetic inputs', 'Target responses', 'Shadow model']) : (zh ? ['影子特征', '成员分类器', 'IN / OUT'] : ['Shadow features', 'Membership classifier', 'IN / OUT'])).map((x, i) => <div className="flow-node" key={x}><small>0{i + 1}</small><strong>{x}</strong>{i < 2 && <span aria-hidden="true"><ArrowIcon direction="right"/></span>}</div>)}</div> :
                kind === 'aloa' ? <svg viewBox="0 0 700 350" role="img" aria-label={zh ? '用户与物品双塔及其输出嵌入示意' : 'User and item towers with illustrative output embeddings'}><g stroke="#686961" fill="none"><path d="M190 55V100M510 55V100M190 255V285L350 315M510 255V285L350 315"/></g>{[190, 510].map((x, i) => <g key={x}><text x={x} y="35" textAnchor="middle" fill="#f6f3ec" fontSize="13">{i ? (zh ? '物品输入' : 'ITEM INPUT') : (zh ? '用户输入' : 'USER INPUT')}</text>{[0, 1, 2].map(j => <g key={j}><path d={`M${x - 70} ${100 + j * 48}l70 -24 70 24v42l-70 24 -70 -24z`} fill="#252623" stroke="#74756b"/><circle cx={x - 30} cy={112 + j * 48} r="4" fill={i ? '#c6c9ba' : '#ff6559'}/></g>)}</g>)}{step === 2 && <circle className="input-signal" cx="190" cy="97" r="6" fill="#ff6559"/>}{Array.from({ length: 12 }, (_, i) => <circle key={i} className={i < 6 ? "output-dot" : undefined} cx={320 + i % 6 * 12} cy={i < 6 ? (step === 2 ? 295 : 310) : 323} r="3" fill={i < 6 ? '#ff6559' : '#c6c9ba'}/>)}</svg> :
                    kind === 'elementization' ? <svg viewBox="0 0 900 300" role="img" aria-label={zh ? '结构化记录通过不透明变换生成计算元素' : 'Structured records pass through an opaque transformation into elements'}><g stroke="#64655d" fill="#262722">{[80, 130, 180].map(y => <rect key={y} x="90" y={y} width="150" height="35" rx="4"/>)}<path d="M250 150H350M550 150H650" fill="none" strokeDasharray="4 6"/><rect x="350" y="60" width="200" height="180" stroke="#ff6559"/></g><text x="450" y="145" textAnchor="middle" fill="#f6f3ec" fontSize="16">ELEMENTIZATION</text><text x="450" y="170" textAnchor="middle" fill="#b8b5ae" fontSize="12">{zh ? '私有变换' : 'Private transformation'}</text><circle cx="730" cy="150" r="90" stroke={step === 2 ? '#ff6559' : '#58594f'} strokeDasharray={step === 2 ? '5 5' : undefined} fill="none"/>{Array.from({ length: 30 }, (_, i) => { const a = i * 2.4, r = Math.sqrt(i / 30) * 70; return <circle key={i} className="lab-dot" cx={730 + Math.cos(a) * r} cy={150 + Math.sin(a) * r} r="3" fill="#ff6559" opacity={step === 0 ? .15 : 1}/>; })}<text x="165" y="275" textAnchor="middle" fill="#b8b5ae" fontSize="12">{zh ? '结构化记录' : 'STRUCTURED RECORDS'}</text><text x="730" y="275" textAnchor="middle" fill="#b8b5ae" fontSize="12">{zh ? '计算元素' : 'COMPUTATIONAL ELEMENTS'}</text></svg> :
                        <div className="learning-card"><small>{zh ? '概念工作流' : 'CONCEPT WORKFLOW'}</small><h3>{(zh ? ['理解一个概念', '展示你的思路', '反思并继续'] : ['Understand a concept', 'Show your reasoning', 'Reflect and continue'])[step]}</h3><div className="learning-lines"><i /><i /><i /></div><p>{(zh ? ['目标 →︎ 练习 →︎ 复盘', '尝试 →︎ 检查 →︎ 人工指导', '解释 →︎ 反馈 →︎ 下一步'] : ['Goal →︎ Practice →︎ Reflection', 'Attempt →︎ Check →︎ Human guidance', 'Explanation →︎ Feedback →︎ Next step'])[step]}</p></div>}
 </div><div className="lab-tabs" role="group" aria-label={zh ? '讲解步骤' : 'Explainer steps'}>{labels.map((label, i) => <button key={label} aria-pressed={i === step} onClick={() => setStep(i)}>{String(i + 1).padStart(2, '0')} {label}</button>)}</div><p className="lab-description" aria-live="polite">{descriptions[step]}</p>{kind==='aloa'&&<div className="visual-facts"><div><small>{zh?'当前观察':'OBSERVE'}</small><span>{(zh?['用户与物品嵌入','目标响应','输入改变后的响应','成员分类信号','报告的准确率']:['User & item embeddings','Target responses','Response to an input change','Membership signal','Reported accuracy'])[step]}</span></div><div><small>{zh?'区分':'DISTINGUISH'}</small><span>{(zh?['两种输入，两个塔','影子模型并非目标模型','分布变化 ≠ 成员概率','成员身份 ≠ 记录重建','不同类别比例']:['Two inputs, two towers','Shadow ≠ target model','Distribution shift ≠ probability','Membership ≠ reconstruction','Different class balances'])[step]}</span></div></div>}<small className="lab-disclosure">{zh ? '示意演示 · 非实测坐标或在线模型' : 'Illustrative demonstration · Not measured coordinates or a live model'}</small></div>;
}
